//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Adress_DB.My.Resources {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Hauptform {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Hauptform() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Adress_DB.Hauptform", typeof(Hauptform).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _BenutzerlisteToolStripMenuItem_Image {
            get {
                object obj = ResourceManager.GetObject("_BenutzerlisteToolStripMenuItem.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _BTN_MapsSuche_Image {
            get {
                object obj = ResourceManager.GetObject("_BTN_MapsSuche.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _BTN_ZuOutlook_Image {
            get {
                object obj = ResourceManager.GetObject("_BTN_ZuOutlook.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=13,Y=12}.
        /// </summary>
        internal static System.Drawing.Point _WSL_AdressenDataSet_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("_WSL_AdressenDataSet.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=342,Y=65}.
        /// </summary>
        internal static System.Drawing.Point AdressenBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("AdressenBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=537,Y=64}.
        /// </summary>
        internal static System.Drawing.Point AdressenTableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("AdressenTableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool AdresstypLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("AdresstypLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool AdresstypLabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("AdresstypLabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool AnredeLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("AnredeLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool AnredeLabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("AnredeLabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=777,Y=149}.
        /// </summary>
        internal static System.Drawing.Point AT_PLZ_GeodatenBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("AT_PLZ_GeodatenBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=996,Y=146}.
        /// </summary>
        internal static System.Drawing.Point AT_PLZ_GeodatenTableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("AT_PLZ_GeodatenTableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=342,Y=115}.
        /// </summary>
        internal static System.Drawing.Point BelegeBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("BelegeBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=346,Y=189}.
        /// </summary>
        internal static System.Drawing.Point BelegeMitAdresseBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("BelegeMitAdresseBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=561,Y=191}.
        /// </summary>
        internal static System.Drawing.Point BelegeMitAdresseTableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("BelegeMitAdresseTableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=525,Y=116}.
        /// </summary>
        internal static System.Drawing.Point BelegeTableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("BelegeTableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool BundeslandLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("BundeslandLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool BundeslandLabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("BundeslandLabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=757,Y=119}.
        /// </summary>
        internal static System.Drawing.Point CH_PLZ_GeodatenBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("CH_PLZ_GeodatenBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=987,Y=119}.
        /// </summary>
        internal static System.Drawing.Point CH_PLZ_GeodatenTableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("CH_PLZ_GeodatenTableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool DatumLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("DatumLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=773,Y=98}.
        /// </summary>
        internal static System.Drawing.Point DE_PLZ_GeodatenBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("DE_PLZ_GeodatenBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=988,Y=96}.
        /// </summary>
        internal static System.Drawing.Point DE_PLZ_GeodatenTableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("DE_PLZ_GeodatenTableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool DirekterKontaktLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("DirekterKontaktLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=341,Y=161}.
        /// </summary>
        internal static System.Drawing.Point DocuwareCSVBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("DocuwareCSVBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=534,Y=163}.
        /// </summary>
        internal static System.Drawing.Point DocuwareCSVTableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("DocuwareCSVTableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool DurchwahlLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("DurchwahlLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool EmailAddresseLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("EmailAddresseLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool EmailAddresseLabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("EmailAddresseLabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool EmailLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("EmailLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool FaxnummerLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("FaxnummerLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool FaxnummerLabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("FaxnummerLabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool FaxnummerLabel3_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("FaxnummerLabel3.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=339,Y=14}.
        /// </summary>
        internal static System.Drawing.Point FirmenNameBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("FirmenNameBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=525,Y=14}.
        /// </summary>
        internal static System.Drawing.Point FirmenNameTableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("FirmenNameTableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie True.
        /// </summary>
        internal static bool IDAdresse_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("IDAdresse.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool IDAdresseLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("IDAdresseLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie True.
        /// </summary>
        internal static bool IDKonto_UserAddedColumn {
            get {
                object obj = ResourceManager.GetObject("IDKonto.UserAddedColumn", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool IDKontoLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("IDKontoLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool IDKontoLabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("IDKontoLabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool IDLKontoLabel2_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("IDLKontoLabel2.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool JobtitleLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("JobtitleLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=29,Y=151}.
        /// </summary>
        internal static System.Drawing.Point klassenBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("klassenBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=36,Y=176}.
        /// </summary>
        internal static System.Drawing.Point klassenTableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("klassenTableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=19,Y=98}.
        /// </summary>
        internal static System.Drawing.Point klassifizierungBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("klassifizierungBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=19,Y=123}.
        /// </summary>
        internal static System.Drawing.Point klassifizierungTableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("klassifizierungTableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=340,Y=91}.
        /// </summary>
        internal static System.Drawing.Point KontakteBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("KontakteBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=348,Y=213}.
        /// </summary>
        internal static System.Drawing.Point KontakteMitAdresseBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("KontakteMitAdresseBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=578,Y=219}.
        /// </summary>
        internal static System.Drawing.Point KontakteMitAdresseTableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("KontakteMitAdresseTableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=539,Y=92}.
        /// </summary>
        internal static System.Drawing.Point KontakteTableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("KontakteTableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=339,Y=40}.
        /// </summary>
        internal static System.Drawing.Point KontoBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("KontoBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=532,Y=38}.
        /// </summary>
        internal static System.Drawing.Point KontoTableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("KontoTableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool LandLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("LandLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=776,Y=36}.
        /// </summary>
        internal static System.Drawing.Point LogTabelleBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("LogTabelleBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=986,Y=41}.
        /// </summary>
        internal static System.Drawing.Point LogTabelleTableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("LogTabelleTableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=15,Y=44}.
        /// </summary>
        internal static System.Drawing.Point MenuStrip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("MenuStrip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MI_Administration_Image {
            get {
                object obj = ResourceManager.GetObject("MI_Administration.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool MobiltelefonLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("MobiltelefonLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool MobiltelefonLabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("MobiltelefonLabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool NachnameLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("NachnameLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool NachnameLabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("NachnameLabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool OrtLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("OrtLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool OrtLabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("OrtLabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pictureBox1_Image {
            get {
                object obj = ResourceManager.GetObject("pictureBox1.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pictureBox2_Image {
            get {
                object obj = ResourceManager.GetObject("pictureBox2.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool PLZLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("PLZLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool PLZLabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("PLZLabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool PLZLabel2_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("PLZLabel2.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool PositionLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("PositionLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool PositionLabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("PositionLabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool PostfachLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("PostfachLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool PostfachLabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("PostfachLabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=773,Y=62}.
        /// </summary>
        internal static System.Drawing.Point PropertiesBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("PropertiesBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=987,Y=67}.
        /// </summary>
        internal static System.Drawing.Point PropertiesTableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("PropertiesTableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=772,Y=11}.
        /// </summary>
        internal static System.Drawing.Point SachbearbeiterBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("SachbearbeiterBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool SachbearbeiterLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("SachbearbeiterLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=978,Y=14}.
        /// </summary>
        internal static System.Drawing.Point SachbearbeiterTableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("SachbearbeiterTableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=787,Y=179}.
        /// </summary>
        internal static System.Drawing.Point StaatenBindingSource_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("StaatenBindingSource.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=1001,Y=179}.
        /// </summary>
        internal static System.Drawing.Point StaatenTableAdapter_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("StaatenTableAdapter.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=21,Y=70}.
        /// </summary>
        internal static System.Drawing.Point StatusStrip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("StatusStrip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool StraßeLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("StraßeLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool StraßeLabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("StraßeLabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=178,Y=14}.
        /// </summary>
        internal static System.Drawing.Point TableAdapterManager_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("TableAdapterManager.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool TelefonGeschaeftlichLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("TelefonGeschaeftlichLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool TelefonGeschaeftlichLabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("TelefonGeschaeftlichLabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool TelefonPrivatLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("TelefonPrivatLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool TelefonPrivatLabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("TelefonPrivatLabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool ThemaLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("ThemaLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Drawing.Point ähnlich wie {X=138,Y=42}.
        /// </summary>
        internal static System.Drawing.Point toolTip1_TrayLocation {
            get {
                object obj = ResourceManager.GetObject("toolTip1.TrayLocation", resourceCulture);
                return ((System.Drawing.Point)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool UStIdNrLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("UStIdNrLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool UStIdNrLabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("UStIdNrLabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool VonWemBesuchtLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("VonWemBesuchtLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool VornameLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("VornameLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool VornameLabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("VornameLabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool WebseiteLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("WebseiteLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool WebseiteLabel1_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("WebseiteLabel1.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool WeitereBesucherLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("WeitereBesucherLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Ressource vom Typ System.Boolean ähnlich wie False.
        /// </summary>
        internal static bool WeitereKontakteLabel_GenerateMember {
            get {
                object obj = ResourceManager.GetObject("WeitereKontakteLabel.GenerateMember", resourceCulture);
                return ((bool)(obj));
            }
        }
    }
}
